#if DEBUG
import HIGTokensComponent
import HIGTokensSemantic

public struct HIGComponentPreviewTheme: HIGTheme {
    public let name = "Preview"
    public let colors: any HIGColorSemanticTokens = HIGSystemColorSemanticTokens()
    public let typography: any HIGTypographySemanticTokens = HIGSystemTypographySemanticTokens()
    public let spacing: any HIGSpacingSemanticTokens = HIGSystemSpacingSemanticTokens()
    public let opacity: any HIGOpacitySemanticTokens = HIGSystemOpacitySemanticTokens()
    public let border: any HIGBorderSemanticTokens = HIGSystemBorderSemanticTokens()
    public let motion: any HIGMotionSemanticTokens = HIGSystemMotionSemanticTokens()
    public let divider: any HIGDividerTokens = HIGSystemDividerTokens()
    public let button: any HIGButtonTokens = HIGSystemButtonTokens()
    public let buttonGroup: any HIGButtonGroupTokens = HIGSystemButtonGroupTokens()
    public let menuToggle: any HIGMenuToggleTokens = HIGSystemMenuToggleTokens()
    public let textField: any HIGTextFieldTokens = HIGSystemTextFieldTokens()
    public let inputGroup: any HIGInputGroupTokens = HIGSystemInputGroupTokens()
    public let fieldMessage: any HIGFieldMessageTokens = HIGSystemFieldMessageTokens()
    public let toggle: any HIGToggleTokens = HIGSystemToggleTokens()
    public let checkbox: any HIGCheckboxTokens = HIGSystemCheckboxTokens()
    public let radio: any HIGRadioTokens = HIGSystemRadioTokens()
    public let segmentedControl: any HIGSegmentedControlTokens = HIGSystemSegmentedControlTokens()
    public let slider: any HIGSliderTokens = HIGSystemSliderTokens()
    public let picker: any HIGPickerTokens = HIGSystemPickerTokens()
    public let card: any HIGCardTokens = HIGSystemCardTokens()
    public let panel: any HIGPanelTokens = HIGSystemPanelTokens()
    public let breadcrumb: any HIGBreadcrumbTokens = HIGSystemBreadcrumbTokens()
    public let pageHeader: any HIGPageHeaderTokens = HIGSystemPageHeaderTokens()
    public let pagination: any HIGPaginationTokens = HIGSystemPaginationTokens()
    public let tabs: any HIGTabsTokens = HIGSystemTabsTokens()
    public let accordion: any HIGAccordionTokens = HIGSystemAccordionTokens()
    public let steps: any HIGStepsTokens = HIGSystemStepsTokens()
    public let pearlSteps: any HIGPearlStepsTokens = HIGSystemPearlStepsTokens()
    public let timeline: any HIGTimelineTokens = HIGSystemTimelineTokens()
    public let statusIndicator: any HIGStatusIndicatorTokens = HIGSystemStatusIndicatorTokens()
    public let emptyState: any HIGEmptyStateTokens = HIGSystemEmptyStateTokens()
    public let closeButton: any HIGCloseButtonTokens = HIGSystemCloseButtonTokens()
    public let modal: any HIGModalTokens = HIGSystemModalTokens()
    public let tooltip: any HIGTooltipTokens = HIGSystemTooltipTokens()
    public let popover: any HIGPopoverTokens = HIGSystemPopoverTokens()
    public let drawer: any HIGDrawerTokens = HIGSystemDrawerTokens()
    public let networkProgressBar: any HIGNetworkProgressBarTokens = HIGSystemNetworkProgressBarTokens()
    public let progress: any HIGProgressTokens = HIGSystemProgressTokens()
    public let alert: any HIGAlertTokens = HIGSystemAlertTokens()
    public let toast: any HIGToastTokens = HIGSystemToastTokens()
    public let badge: any HIGBadgeTokens = HIGSystemBadgeTokens()
    public let icon: any HIGIconTokens = HIGSystemIconTokens()
    public let avatar: any HIGAvatarTokens = HIGSystemAvatarTokens()
    public let link: any HIGLinkTokens = HIGSystemLinkTokens()
    public let bulletList: any HIGBulletListTokens = HIGSystemBulletListTokens()
    public let textEditor: any HIGTextEditorTokens = HIGSystemTextEditorTokens()
    public let stepper: any HIGStepperTokens = HIGSystemStepperTokens()
    public let menuButton: any HIGMenuButtonTokens = HIGSystemMenuButtonTokens()
    public let tag: any HIGTagTokens = HIGSystemTagTokens()
    public let navigationBar: any HIGNavigationBarTokens = HIGSystemNavigationBarTokens()
    public let toolbar: any HIGToolbarTokens = HIGSystemToolbarTokens()
    public let activityIndicator: any HIGActivityIndicatorTokens = HIGSystemActivityIndicatorTokens()
    public let matrixLoader: any HIGMatrixLoaderTokens = HIGSystemMatrixLoaderTokens()
    public let shimmer: any HIGShimmerTokens = HIGSystemShimmerTokens()
    public let list: any HIGListTokens = HIGSystemListTokens()
    public let sidebar: any HIGSidebarTokens = HIGSystemSidebarTokens()
    public let photoPicker: any HIGPhotoPickerTokens = HIGSystemPhotoPickerTokens()
    public let photoEditor: any HIGPhotoEditorTokens = HIGSystemPhotoEditorTokens()
    public let longTextEditor: any HIGLongTextEditorTokens = HIGSystemLongTextEditorTokens()

    public init() {}
}
#endif