#!/usr/bin/env python3
"""Generate Heroicons catalog and Swift token definitions for HIGIcons."""

from __future__ import annotations

import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HEROICONS_ROOT = Path("/Users/andy/github/heroicons/src/24")
OUTPUT_ROOT = Path(__file__).resolve().parent.parent / "Sources" / "HIGIcons"
CATALOG_PATH = OUTPUT_ROOT / "Resources" / "hero-icon-catalog.json"
TOKENS_DIR = OUTPUT_ROOT / "Tokens" / "Generated"
CASES_PER_FILE = 45
STROKE_WIDTH = 1.5
VIEWBOX_SIZE = 24.0


def slug_to_camel(slug: str) -> str:
    parts = slug.split("-")
    return parts[0] + "".join(part.capitalize() for part in parts[1:])


def parse_icon_file(path: Path, variant: str) -> dict:
    root = ET.parse(path).getroot()
    paths: list[dict] = []

    for element in root.iter():
        tag = element.tag.split("}")[-1]
        if tag != "path":
            continue

        path_data = element.attrib.get("d")
        if not path_data:
            continue

        entry: dict[str, object] = {"d": path_data}
        if variant == "outline":
            entry["strokeWidth"] = float(element.attrib.get("stroke-width", STROKE_WIDTH))
        paths.append(entry)

    if not paths:
        raise ValueError(f"No paths found in {path}")

    render_mode = "stroke" if variant == "outline" else "fill"
    return {"paths": paths, "renderMode": render_mode}


def build_catalog() -> dict[str, dict]:
    catalog: dict[str, dict] = {}

    for variant in ("outline", "solid"):
        variant_dir = HEROICONS_ROOT / variant
        if not variant_dir.is_dir():
            raise FileNotFoundError(f"Missing Heroicons directory: {variant_dir}")

        for svg_path in sorted(variant_dir.glob("*.svg")):
            slug = svg_path.stem
            catalog.setdefault(slug, {})[variant] = parse_icon_file(svg_path, variant)

    return catalog


def write_catalog(catalog: dict[str, dict]) -> None:
    CATALOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CATALOG_PATH.write_text(json.dumps(catalog, separators=(",", ":")), encoding="utf-8")


def write_token_files(catalog: dict[str, dict]) -> None:
    TOKENS_DIR.mkdir(parents=True, exist_ok=True)

    for existing in TOKENS_DIR.glob("HIGHeroIconToken+*.swift"):
        existing.unlink()

    slugs = sorted(catalog.keys())
    chunks = [slugs[index : index + CASES_PER_FILE] for index in range(0, len(slugs), CASES_PER_FILE)]

    base_path = TOKENS_DIR / "HIGHeroIconToken.swift"
    base_path.write_text(
        """// Generated by Scripts/generate_hero_icons.py. Do not edit manually.

import Foundation

/// A type-safe Heroicons v2 24pt icon identifier.
public struct HIGHeroIconToken: Hashable, Sendable, Codable, CaseIterable {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public static let allCases: [HIGHeroIconToken] = [
"""
        + ",\n".join(f"        .{slug_to_camel(slug)}" for slug in slugs)
        + """
    ]
}
""",
        encoding="utf-8",
    )

    for index, chunk in enumerate(chunks):
        lines = [
            "// Generated by Scripts/generate_hero_icons.py. Do not edit manually.",
            "",
            "extension HIGHeroIconToken {",
        ]
        for slug in chunk:
            lines.append(f'    public static let {slug_to_camel(slug)} = HIGHeroIconToken(rawValue: "{slug}")')
        lines.append("}")
        lines.append("")

        file_path = TOKENS_DIR / f"HIGHeroIconToken+Chunk{index + 1}.swift"
        file_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if not HEROICONS_ROOT.is_dir():
        print(f"Heroicons source not found: {HEROICONS_ROOT}", file=sys.stderr)
        return 1

    catalog = build_catalog()
    write_catalog(catalog)
    write_token_files(catalog)
    print(f"Generated {len(catalog)} icons into {OUTPUT_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())