import HIGShowcase
import Testing

@Test
func showcaseCatalogIncludesLongTextEditor() {
    let titles = ShowcaseComponent.allCases.map(\.title)
    #expect(ShowcaseComponent.allCases.count == 127)
    #expect(titles.contains("Photo Editor"))
    #expect(titles.contains("Long Text Editor"))
    #expect(titles.contains("Matrix Loader"))
    #expect(titles.contains("Panel"))
    #expect(titles.contains("Breadcrumb"))
    #expect(titles.contains("Page Header"))
    #expect(titles.contains("Pagination"))
    #expect(titles.contains("Tabs"))
    #expect(titles.contains("Accordion"))
    #expect(titles.contains("Steps"))
    #expect(titles.contains("Pearl Steps"))
    #expect(titles.contains("Timeline"))
    #expect(titles.contains("Status Indicator"))
    #expect(titles.contains("Empty State"))
    #expect(titles.contains("Close Button"))
    #expect(titles.contains("Modal"))
    #expect(titles.contains("Tooltip"))
    #expect(titles.contains("Popover"))
    #expect(titles.contains("Drawer"))
    #expect(titles.contains("Confirmation Dialog"))
    #expect(titles.contains("Network Progress Bar"))
    #expect(titles.contains("Button Group"))
    #expect(titles.contains("Menu Toggle"))
    #expect(titles.contains("Input Group"))
    #expect(titles.contains("Field Message"))
    #expect(titles.contains("Date Picker"))
    #expect(titles.contains("Time Picker"))
    #expect(titles.contains("Select"))
    #expect(titles.contains("Autocomplete"))
    #expect(titles.contains("Tag Input"))
    #expect(titles.contains("Data Table"))
    #expect(titles.contains("Drop Zone"))
    #expect(titles.contains("Admin Shell"))
    #expect(titles.contains("Code Block"))
    #expect(titles.contains("Carousel"))
    #expect(titles.contains("Media Row"))
    #expect(titles.contains("Hero"))
    #expect(titles.contains("List Group"))
    #expect(titles.contains("Bar Chart"))
    #expect(titles.contains("Line Chart"))
    #expect(titles.contains("Pie Chart"))
    #expect(titles.contains("Area Chart"))
    #expect(titles.contains("Lightbox"))
    #expect(titles.contains("Counter"))
    #expect(titles.contains("Widget"))
    #expect(titles.contains("Panel Group"))
    #expect(titles.contains("Rating"))
    #expect(titles.contains("Testimonial"))
    #expect(titles.contains("Ribbon"))
    #expect(titles.contains("Pricing Card"))
    #expect(titles.contains("Chat Bubble"))
    #expect(titles.contains("Comment"))
    #expect(titles.contains("Cover"))
    #expect(titles.contains("Image Overlay"))
    #expect(titles.contains("Color Selector"))
    #expect(titles.contains("Social Button"))
    #expect(titles.contains("Image Frame"))
    #expect(titles.contains("Tree View"))
    #expect(titles.contains("Reorderable List"))
    #expect(titles.contains("Calendar"))
    #expect(titles.contains("Dashboard Grid"))
    #expect(titles.contains("Video Player"))
    #expect(titles.contains("Coach Mark"))
    #expect(titles.contains("Map"))
    #expect(titles.contains("Mailbox App"))
    #expect(titles.contains("Taskboard App"))
    #expect(titles.contains("Work App"))
    #expect(titles.contains("Login Page"))
    #expect(titles.contains("Error Pages"))
    #expect(titles.contains("Email Templates Page"))
    #expect(ShowcaseComponent.allCases.last?.title == "Email Templates Page")

    let componentIDs = Set(ShowcaseComponent.catalogSorted(in: .components).map(\.id))
    let pageIDs = Set(ShowcaseComponent.catalogSorted(in: .pages).map(\.id))
    #expect(componentIDs.isDisjoint(with: pageIDs))
    #expect(componentIDs.union(pageIDs).count == ShowcaseComponent.allCases.count)
    #expect(pageIDs.contains("pageLogin"))
    #expect(pageIDs.contains("appMailbox"))
    #expect(pageIDs.contains("map"))
    #expect(componentIDs.contains("button"))
    #expect(componentIDs.contains("adminShell"))
    #expect(!componentIDs.contains("pageLogin"))
}