import HIGShowcase
import Testing

@Test
func showcaseCatalogIncludesLongTextEditor() {
    let titles = ShowcaseComponent.allCases.map(\.title)
    #expect(ShowcaseComponent.allCases.count == 64)
    #expect(titles.contains("Photo Editor"))
    #expect(titles.contains("Long Text Editor"))
    #expect(titles.contains("Matrix Loader"))
    #expect(titles.contains("Panel"))
    #expect(titles.contains("Breadcrumb"))
    #expect(titles.contains("Page Header"))
    #expect(titles.contains("Pagination"))
    #expect(titles.contains("Tabs"))
    #expect(titles.contains("Accordion"))
    #expect(titles.contains("Steps"))
    #expect(titles.contains("Pearl Steps"))
    #expect(titles.contains("Timeline"))
    #expect(titles.contains("Status Indicator"))
    #expect(titles.contains("Empty State"))
    #expect(titles.contains("Close Button"))
    #expect(titles.contains("Modal"))
    #expect(titles.contains("Tooltip"))
    #expect(titles.contains("Popover"))
    #expect(titles.contains("Drawer"))
    #expect(titles.contains("Confirmation Dialog"))
    #expect(titles.contains("Network Progress Bar"))
    #expect(titles.contains("Button Group"))
    #expect(titles.contains("Menu Toggle"))
    #expect(titles.contains("Input Group"))
    #expect(titles.contains("Field Message"))
    #expect(titles.contains("Date Picker"))
    #expect(titles.contains("Time Picker"))
    #expect(titles.contains("Select"))
    #expect(titles.contains("Autocomplete"))
    #expect(titles.contains("Tag Input"))
    #expect(titles.contains("Data Table"))
    #expect(ShowcaseComponent.allCases.last?.title == "Data Table")
}